services:
  kafka-ui:
    container_name: kafka-ui
    image: provectuslabs/kafka-ui:latest
    ports:
      - 8080:8080
    environment:
      DYNAMIC_CONFIG_ENABLED: true
      LOGGING_LEVEL_ROOT: 'DEBUG'
    volumes:
      - ./kui/config.yml:/etc/kafkaui/dynamic_config.yaml